QuizApp/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger_ui'),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True)), name='graphQL'),
    path('account/', include('account_app.urls')),
    path('', include('quiz_app.urls')),
]

account_app/urls.py
from django.urls import path
from .views import Login, Register, profile_view

app_name = 'account'

urlpatterns = [
    path('login', Login.as_view(), name='login_page'),
    path('register', Register.as_view(), name='register_page'),
    path('profile', profile_view, name='profile_page'),
]

account_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser, Group, Permission


SEX_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other')
]

class Profile(models.Model):
    name = models.CharField(max_length=255)
    tel = models.IntegerField()
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    age = models.PositiveIntegerField()
    field_of_study = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    sleep_time = models.PositiveIntegerField()

    def __str__(self):
        return self.name

account_app/forms.py
from django import forms
from .models import SEX_CHOICES, Profile


class LoginForm(forms.Form):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام خانوادگی'}))

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'آدرس ایمیل'}))

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'رمز عبور'}))
    conf_pass = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'تایید رمز عبور'}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'tel', 'sex', 'age', 'field_of_study', 'city', 'sleep_time']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام'}),
            'tel': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'تلفن'}),
            'sex': forms.Select(attrs={'class': 'form-control', 'placeholder': 'جنسیت'}),
            'age': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'سن'}),
            'field_of_study': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'رشته تحصیلی'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'شهر'}),
            'sleep_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'شب گذشته چند ساعت خوابیده اید'}),
        }

account_app/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.views.generic import View
from .forms import LoginForm, RegisterForm
from .models import Profile
from django.contrib import messages


class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('quiz:quiz_page')
        else:
            form = LoginForm()
            return render(request, 'account_app/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['fullname'], password=cd['password'])

            if user is not None:
                login(request, user, backend="django.contrib.auth.backends.ModelBackend")
                return redirect('quiz:quiz_page')
            else:
                form.add_error('fullname', 'Invalid User Data')

        return render(request, 'account_app/login.html', {'form': form})


class Register(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('quiz:quiz_page')
        else:
            form = RegisterForm()
            return render(request, 'account_app/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            if cd['password'] != cd['conf_pass']:
                form.add_error('password', 'Passwords are not the same !!')
            else:
                fullname = f"{cd['first_name']} {cd['last_name']}"

                user = User.objects.create_user(
                    username=fullname,
                    first_name=cd['first_name'],
                    last_name=cd['last_name'],
                    email=cd['email'],
                    password=cd['password'],)

                login(request, user, backend="django.contrib.auth.backends.ModelBackend")
                return redirect('quiz:quiz_page')
        else:
            form.add_error('password', 'Invalid Data')

        return render(request, 'account_app/register.html', {'form': form})


def profile_view(request):
    if request.method == 'POST':
        namea = request.POST.get('name')
        tela = request.POST.get('tel')
        sexa = request.POST.get('sex')
        agea = request.POST.get('age')
        field = request.POST.get('field')
        citya = request.POST.get('city')
        sleep = request.POST.get('sleep')

        try:
            profile = Profile(name=namea, tel=tela, sex=sexa,
                              age=agea, field_of_study=field,
                              city=citya, sleep_time=sleep)
            profile.save()

            success = True
            message = "ثبت اطلاعات با موفقیت انجام شد"

        except Exception as e:
            message = str(e)

        response_data = {
            "success": success,
            "message": message
        }
        return JsonResponse(response_data)
    else:
        return render(request, 'account_app/profile.html')

account_app/templates/account_app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include 'includes/header.html' %}

<body translate="no">
{# Animated Background #}
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>

<div class="login-page">
    <div class="form">
        <form class="login-form" method="post">
            {% csrf_token %}

            {% for error in form.fullname.errors %}
                <p>{{ error }}</p>
            {% endfor %}

            <input style="font-family: '2  Roya'" type="text" id="fullname" name="fullname" placeholder="نام کاربری" required>

            <input style="font-family: '2  Roya'" type="password" id="password" name="password" placeholder="رمز عبور" required>

            <button type="submit">ورود</button>
            <p class="message">حساب کاربری ندارید؟ <a href="{% url 'account:profile_page' %}">ایجاد حساب</a></p>
        </form>
    </div>
</div>

</body>
</html>

account_app/templates/account_app/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% include 'includes/header.html' %}

<body translate="no">
    <div class="box">
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

    <div class="login-page">
        <div class="form">
            <form class="register-form"
                  method="post"
                  onsubmit="clearForm(event)"
                  id="forms">

                {% csrf_token %}

                <label class="form-label">نام</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="text"
                            class="form-control required alphaonly"
                            placeholder="نام "
                            name="name"/>
                    </div>

                <label class="form-label">سن</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="number"
                            class="form-control required"
                            placeholder="سن"
                            name="age"
                            pattern="\d*"
                            inputmode="numeric"/>
                    </div>

                <label class="form-label">شماره تلفن</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="number"
                            class="form-control required"
                            placeholder="شماره تلفن"
                            pattern="\d*"
                            name="tel"
                            inputmode="numeric"/>
                    </div>

                <label class="form-label">جنسیت</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="text"
                            class="form-control required"
                            pattern="(مرد|زن)"
                            title="لطفا اطلاعات را به درستی وارد کنید : 'مرد' یا 'زن'"
                            placeholder="جنسیت"
                            name="sex"
                            required
                        />
                </div>


                <label class="form-label">رشته</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="text"
                            class="form-control required alphaonly"
                            placeholder="رشته"
                            name="field"/>
                    </div>

                <label class="form-label">شهر</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="text"
                            class="form-control required alphaonly"
                            placeholder="شهر"
                            name="city"/>
                    </div>

                <label class="form-label">شبانه روز گذشته چند ساعت خوابیده اید ؟</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text">
                            <i class="align-middle" data-feather="edit"></i>
                        </span>
                        <input
                            type="number"
                            class="form-control required"
                            placeholder="مدت خواب"
                            name="sleep"
                            pattern="\d*"
                            inputmode="numeric"/>
                    </div>

<div id="success-message"></div>

                <button type="submit">ایجاد</button>
                <p class="message">حساب کاربری دارید؟ <a href="{% url 'account:login_page' %}">ورود</a></p>
            </form>
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  function showToast(title, message) {
    // Display toast message
    console.log(title + ": " + message);
  }

  function clearForm() {
    event.preventDefault(); // Prevent form submission

    var name = document.forms["forms"]["name"].value;
    var age = document.forms["forms"]["age"].value;
    var sex = document.forms["forms"]["sex"].value;
    var field = document.forms["forms"]["field"].value;
    var tel = document.forms["forms"]["tel"].value;
    var sleep = document.forms["forms"]["sleep"].value;
    var city = document.forms["forms"]["city"].value;

    // Reset form data
    var formData = {
        csrfmiddlewaretoken: "{{ csrf_token }}",
        name: name,
        age: age,
        tel: tel,
        sex: sex,
        field: field,
        city: city,
        sleep: sleep
    };

    $.ajax({
      type: "POST",
      url: "{% url 'account:profile_page' %}",
      data: formData,
      dataType: "json",
      success: function(response) {
        if (response.success) {
            $("#success-message").html(response.message);
            $("#success-message").addClass("show");
            setTimeout(function(){
                $("#success-message").html("");
                $("#success-message").removeClass("show");
            }, 3000);
            $('input, textarea').val('');
        } else {
          showToast("اطلاعات ثبت نشده است", response.message);
        }
      },
      error: function() {
        showToast("error", "یک خطایی رخ داده است");
      },
    });

    document.querySelector('.register-form').reset();
  }
</script>

</body>
</html>

account_app/templates/account_app/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include 'includes/header.html' %}

<body translate="no">
{# Animated Background #}
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>

<div class="login-page">
    <div class="form">
        <form class="register-form" method="post">
            {% csrf_token %}

            {% for error in form.password.errors %}
                <p>{{ error }}</p>
            {% endfor %}

            {{ form.first_name }}
            {{ form.last_name }}
            {{ form.sex }}
            {{ form.age }}
            {{ form.field_of_study }}
            {{ form.city }}
            {{ form.sleep_time }}

            <button type="submit">ایجاد</button>
            <p class="message">حساب کاربری دارید؟ <a href="{% url 'account:login_page' %}">ورود</a></p>
        </form>
    </div>
</div>

</body>
</html>